export const players = [
  { id: 'sga', name: 'Shai Gilgeous-Alexander', team: 'OKC', position: 'PG' },
  { id: 'doncic', name: 'Luka Dončić', team: 'LAL', position: 'PG' },
  { id: 'haliburton', name: 'Tyrese Haliburton', team: 'IND', position: 'PG' },
  { id: 'curry', name: 'Stephen Curry', team: 'GSW', position: 'PG' },
  { id: 'cade', name: 'Cade Cunningham', team: 'DET', position: 'PG' },
  { id: 'morant', name: 'Ja Morant', team: 'MEM', position: 'PG' },
  { id: 'edwards', name: 'Anthony Edwards', team: 'MIN', position: 'SG' },
  { id: 'booker', name: 'Devin Booker', team: 'PHX', position: 'SG' },
  { id: 'mitchell', name: 'Donovan Mitchell', team: 'CLE', position: 'SG' },
  { id: 'herro', name: 'Tyler Herro', team: 'MIA', position: 'SG' },
  { id: 'reaves', name: 'Austin Reaves', team: 'LAL', position: 'SG' },
  { id: 'brown', name: 'Jaylen Brown', team: 'BOS', position: 'SG' },
  { id: 'tatum', name: 'Jayson Tatum', team: 'BOS', position: 'SF' },
  { id: 'durant', name: 'Kevin Durant', team: 'HOU', position: 'SF' },
  { id: 'lebron', name: 'LeBron James', team: 'LAL', position: 'SF' },
  { id: 'franz', name: 'Franz Wagner', team: 'ORL', position: 'SF' },
  { id: 'kawhi', name: 'Kawhi Leonard', team: 'LAC', position: 'SF' },
  { id: 'bridges', name: 'Mikal Bridges', team: 'NYK', position: 'SF' },
  { id: 'giannis', name: 'Giannis Antetokounmpo', team: 'MIL', position: 'PF' },
  { id: 'paolo', name: 'Paolo Banchero', team: 'ORL', position: 'PF' },
  { id: 'zion', name: 'Zion Williamson', team: 'NOP', position: 'PF' },
  { id: 'randle', name: 'Julius Randle', team: 'MIN', position: 'PF' },
  { id: 'jjj', name: 'Jaren Jackson Jr.', team: 'MEM', position: 'PF' },
  { id: 'jokic', name: 'Nikola Jokić', team: 'DEN', position: 'C' },
  { id: 'wembanyama', name: 'Victor Wembanyama', team: 'SAS', position: 'C' },
  { id: 'davis', name: 'Anthony Davis', team: 'DAL', position: 'C' },
  { id: 'embiid', name: 'Joel Embiid', team: 'PHI', position: 'C' },
  { id: 'sabonis', name: 'Domantas Sabonis', team: 'SAC', position: 'C' },
  { id: 'towns', name: 'Karl-Anthony Towns', team: 'NYK', position: 'C' },
  { id: 'bam', name: 'Bam Adebayo', team: 'MIA', position: 'C' },
]

export const playersById = new Map(players.map((player) => [player.id, player]))
